/// The kalendar RRULE subset (`docs/plan.md` §12 phase-2 DoD: "kalendar
/// RRULE subset") — a hand-written parser and expander for a deliberately
/// small slice of RFC 5545 `RRULE`, precise enough to test and reason
/// about. No external RRULE package is used: the supported subset is
/// small enough that hand-writing it is simpler (and easier to audit for
/// the "never throw, never loop forever" requirements below) than vetting
/// a general-purpose dependency against them.
///
/// ## Supported subset
///
/// - `FREQ=DAILY` | `FREQ=WEEKLY` | `FREQ=MONTHLY` — required; any other
///   value (`YEARLY`, `HOURLY`, ...) is unsupported.
/// - `INTERVAL=<positive integer>` — default 1.
/// - `COUNT=<positive integer>` — total number of occurrences in the
///   whole series (not just the queried range). Mutually exclusive with
///   `UNTIL` per RFC 5545; if a rule string somehow carries both, `COUNT`
///   wins and `UNTIL` is ignored (documented, deterministic — not treated
///   as malformed).
/// - `UNTIL=<YYYYMMDD>` or `UNTIL=<YYYYMMDDTHHMMSSZ>` — **inclusive**: an
///   occurrence landing exactly on `UNTIL` is kept. A date-only `UNTIL`
///   compares by calendar date alone (any occurrence on that day counts,
///   regardless of time-of-day or the event's own UTC/local-ness); a
///   `...Z` date-time `UNTIL` is an absolute UTC instant compared against
///   each occurrence converted to UTC.
/// - `BYDAY=<comma list of MO,TU,WE,TH,FR,SA,SU>` — supported **only**
///   combined with `FREQ=WEEKLY`. No numbered prefix (`2MO`, `-1FR`) is
///   supported. Combined with `DAILY`/`MONTHLY`, or carrying a numbered
///   prefix, the whole rule is unsupported (see degrade rule below).
/// - `WKST=<MO|TU|WE|TH|FR|SA|SU>` — default `MO`. Only matters for
///   `WEEKLY` with `INTERVAL>1`: it decides where a "week" starts, which
///   in turn decides which BYDAY dates fall in the same interval-week as
///   which others (see the week-start test in
///   `test/features/calendar/domain/recurrence_test.dart`).
///
/// **Explicitly NOT supported** (any of these anywhere in the string
/// degrades the whole rule, per the rule below): `FREQ=YEARLY`/`HOURLY`/
/// `MINUTELY`/`SECONDLY`, `BYMONTH`, `BYMONTHDAY`, `BYYEARDAY`,
/// `BYWEEKNO`, `BYSETPOS`, `BYHOUR`/`BYMINUTE`/`BYSECOND`, `RDATE`/
/// `EXDATE`/`EXRULE` (those are separate iCalendar properties, not part of
/// `RRULE`, and are out of scope here regardless), a numbered `BYDAY`
/// prefix, lower/mixed-case keys or values, and combining `COUNT` in a
/// way this parser cannot read as a plain positive integer.
///
/// ## Degrade rule
///
/// A `null`/empty [CalendarEvent.rrule], or one this parser cannot fully
/// place into the subset above, **never throws** — it degrades to a
/// single occurrence at the event's own [CalendarEvent.startAt] (kept
/// only if that instant falls in the queried range). This matters because
/// RRULE strings arrive over sync from other clients/app versions that
/// may read or write a wider subset than this file does.
///
/// ## The 31st-of-the-month rule
///
/// For `FREQ=MONTHLY`, a target month that doesn't have the start day's
/// day-of-month (e.g. day 31 landing on a 30-day month, or day 29/30/31
/// landing on a non-leap February) is **skipped entirely** — no
/// occurrence is generated for that month, and the day-of-month is never
/// clamped to the month's last day. Rationale: clamping would make
/// "day-of-month" drift (a 31st-of-the-month rule would sometimes land on
/// the 28th, 29th or 30th) and silently reinterpret what the user asked
/// for; skipping keeps the invariant "every occurrence is on the exact
/// same day-of-month, or it doesn't happen that month" — the same choice
/// several mainstream calendar apps make for this exact case.
///
/// ## DST
///
/// Occurrences are generated by keeping the event's wall-clock
/// hour/minute/second/millisecond/microsecond fixed and only ever
/// stepping the *calendar date* (year/month/day) — never by adding a
/// fixed [Duration] to an instant. A [Duration] addition would silently
/// shift the wall-clock hour whenever the step crosses a DST transition
/// (e.g. adding exactly 168 hours across a spring-forward would land one
/// hour "later" on the wall clock); reconstructing the next occurrence
/// from date components instead — via the same constructor family
/// (`DateTime.utc`, plain local `DateTime`, or `TZDateTime` for an
/// explicit IANA location) the original [CalendarEvent.startAt] used —
/// lets Dart (or `package:timezone`, already a project dependency used
/// for notification scheduling) resolve the correct UTC offset for that
/// date, so the wall-clock time never drifts across the boundary.
///
/// ## Laziness / boundedness
///
/// Occurrence generation is a lazy Dart generator (`sync*`) that is only
/// ever consumed through [expandRruleOccurrences]/[expandEventOccurrences],
/// both of which stop pulling from it as soon as a candidate exceeds the
/// requested range end (or `COUNT`/`UNTIL` terminates the series first) —
/// an unbounded rule (no `COUNT`/`UNTIL`) is a legitimately infinite lazy
/// sequence in Dart, but it is never materialized into a `List` before
/// being bounded by the caller's date range, so memory use is always
/// proportional to the number of occurrences actually inside the queried
/// range, never to the full (possibly unbounded) series.
library;

import 'package:timezone/timezone.dart' show TZDateTime;

import '../../../core/db/app_database.dart' show CalendarEvent;

/// One concrete occurrence of a (possibly recurring) [CalendarEvent]
/// inside a queried range.
class CalendarOccurrence {
  const CalendarOccurrence({
    required this.event,
    required this.start,
    required this.end,
  });

  final CalendarEvent event;
  final DateTime start;

  /// `null` when the source event has no [CalendarEvent.endAt] (an
  /// open-ended/point-in-time event) — see `calendar_events_table.dart`.
  final DateTime? end;
}

/// Expands [event] into its concrete occurrences inside
/// `[rangeStart, rangeEnd]` (both inclusive), preserving the event's own
/// duration ([CalendarEvent.endAt] minus [CalendarEvent.startAt], if any)
/// on every occurrence. See the file doc for the supported `RRULE` subset
/// and the degrade rule.
List<CalendarOccurrence> expandEventOccurrences(
  CalendarEvent event, {
  required DateTime rangeStart,
  required DateTime rangeEnd,
}) {
  final starts = expandRruleOccurrences(
    rrule: event.rrule,
    dtstart: event.startAt,
    rangeStart: rangeStart,
    rangeEnd: rangeEnd,
  );
  final endAt = event.endAt;
  final duration = endAt?.difference(event.startAt);
  return [
    for (final start in starts)
      CalendarOccurrence(
        event: event,
        start: start,
        end: duration == null ? null : start.add(duration),
      ),
  ];
}

/// The lower-level entry point: expands a raw `rrule` string (as stored in
/// [CalendarEvent.rrule]) anchored at [dtstart] into occurrence start
/// times inside `[rangeStart, rangeEnd]` (both inclusive). Exposed
/// separately from [expandEventOccurrences] so recurrence rules can be
/// unit-tested without constructing a full [CalendarEvent].
List<DateTime> expandRruleOccurrences({
  required String? rrule,
  required DateTime dtstart,
  required DateTime rangeStart,
  required DateTime rangeEnd,
}) {
  if (rrule == null || rrule.trim().isEmpty) {
    return _singleOccurrence(dtstart, rangeStart, rangeEnd);
  }
  final parsed = _tryParse(rrule);
  if (parsed == null) {
    return _singleOccurrence(dtstart, rangeStart, rangeEnd);
  }
  return _occurrencesInRange(parsed, dtstart, rangeStart, rangeEnd);
}

List<DateTime> _singleOccurrence(
  DateTime dtstart,
  DateTime rangeStart,
  DateTime rangeEnd,
) {
  final inRange = !dtstart.isBefore(rangeStart) && !dtstart.isAfter(rangeEnd);
  return inRange ? [dtstart] : const [];
}

// --- Parsing -----------------------------------------------------------

enum _Freq { daily, weekly, monthly }

const Map<String, int> _weekdayCodes = {
  'MO': DateTime.monday,
  'TU': DateTime.tuesday,
  'WE': DateTime.wednesday,
  'TH': DateTime.thursday,
  'FR': DateTime.friday,
  'SA': DateTime.saturday,
  'SU': DateTime.sunday,
};

class _Until {
  const _Until.dateOnly(
      {required this.year, required this.month, required this.day})
      : instant = null;

  const _Until.instant(DateTime this.instant)
      : year = null,
        month = null,
        day = null;

  final int? year;
  final int? month;
  final int? day;
  final DateTime? instant;

  /// Whether [occurrence] is on or before this `UNTIL` — inclusive, per
  /// RFC 5545 and this file's doc.
  bool includes(DateTime occurrence) {
    final instant = this.instant;
    if (instant != null) {
      final occUtc = occurrence.isUtc ? occurrence : occurrence.toUtc();
      return !occUtc.isAfter(instant);
    }
    final occValue =
        occurrence.year * 10000 + occurrence.month * 100 + occurrence.day;
    final untilValue = year! * 10000 + month! * 100 + day!;
    return occValue <= untilValue;
  }
}

class _ParsedRecurrence {
  const _ParsedRecurrence({
    required this.freq,
    required this.interval,
    required this.byDay,
    required this.weekStart,
    required this.count,
    required this.until,
  });

  final _Freq freq;
  final int interval;

  /// Empty means "the same weekday as `DTSTART`" — only meaningful (and
  /// only ever non-empty) for [_Freq.weekly].
  final Set<int> byDay;
  final int weekStart;
  final int? count;
  final _Until? until;
}

final RegExp _untilDateOnly = RegExp(r'^\d{8}$');
final RegExp _untilDateTimeUtc = RegExp(r'^\d{8}T\d{6}Z$');

_Until? _parseUntil(String value) {
  if (_untilDateOnly.hasMatch(value)) {
    return _Until.dateOnly(
      year: int.parse(value.substring(0, 4)),
      month: int.parse(value.substring(4, 6)),
      day: int.parse(value.substring(6, 8)),
    );
  }
  if (_untilDateTimeUtc.hasMatch(value)) {
    return _Until.instant(
      DateTime.utc(
        int.parse(value.substring(0, 4)),
        int.parse(value.substring(4, 6)),
        int.parse(value.substring(6, 8)),
        int.parse(value.substring(9, 11)),
        int.parse(value.substring(11, 13)),
        int.parse(value.substring(13, 15)),
      ),
    );
  }
  return null;
}

/// Parses [rrule] into the supported subset, or returns `null` for
/// anything unparseable/unsupported — see the file doc's degrade rule.
/// Never throws: every failure path is an explicit `return null`, and the
/// only exception-prone calls ([int.parse]) are always guarded by
/// [int.tryParse] or a regex match first.
_ParsedRecurrence? _tryParse(String rrule) {
  _Freq? freq;
  var interval = 1;
  int? count;
  _Until? until;
  final byDay = <int>{};
  var weekStart = DateTime.monday;

  for (final part in rrule.split(';')) {
    if (part.isEmpty) continue;
    final eq = part.indexOf('=');
    if (eq <= 0 || eq == part.length - 1) return null;
    final key = part.substring(0, eq);
    final value = part.substring(eq + 1);

    switch (key) {
      case 'FREQ':
        switch (value) {
          case 'DAILY':
            freq = _Freq.daily;
          case 'WEEKLY':
            freq = _Freq.weekly;
          case 'MONTHLY':
            freq = _Freq.monthly;
          default:
            return null;
        }
      case 'INTERVAL':
        final n = int.tryParse(value);
        if (n == null || n < 1) return null;
        interval = n;
      case 'COUNT':
        final n = int.tryParse(value);
        if (n == null || n < 1) return null;
        count = n;
      case 'UNTIL':
        final parsedUntil = _parseUntil(value);
        if (parsedUntil == null) return null;
        until = parsedUntil;
      case 'BYDAY':
        for (final code in value.split(',')) {
          final weekday = _weekdayCodes[code];
          if (weekday == null) return null; // rejects numbered prefixes too
          byDay.add(weekday);
        }
      case 'WKST':
        final weekday = _weekdayCodes[value];
        if (weekday == null) return null;
        weekStart = weekday;
      default:
        return null; // any part outside the supported subset
    }
  }

  if (freq == null) return null; // FREQ is mandatory in this subset
  if (byDay.isNotEmpty && freq != _Freq.weekly) return null;

  return _ParsedRecurrence(
    freq: freq,
    interval: interval,
    byDay: byDay,
    weekStart: weekStart,
    count: count,
    until: until,
  );
}

// --- Expansion -----------------------------------------------------------

/// Reconstructs a [DateTime] on the given calendar date, keeping [base]'s
/// wall-clock time-of-day and its exact "kind" (`TZDateTime` at the same
/// location, plain UTC, or plain local) — see the file doc's DST section.
DateTime _atDate(DateTime base,
    {required int year, required int month, required int day}) {
  if (base is TZDateTime) {
    return TZDateTime(
      base.location,
      year,
      month,
      day,
      base.hour,
      base.minute,
      base.second,
      base.millisecond,
      base.microsecond,
    );
  }
  if (base.isUtc) {
    return DateTime.utc(
      year,
      month,
      day,
      base.hour,
      base.minute,
      base.second,
      base.millisecond,
      base.microsecond,
    );
  }
  return DateTime(
    year,
    month,
    day,
    base.hour,
    base.minute,
    base.second,
    base.millisecond,
    base.microsecond,
  );
}

/// [base] shifted by [days] whole calendar days (may be negative), keeping
/// wall-clock time. The day arithmetic itself is done in a neutral UTC
/// calendar (no DST in UTC), then re-anchored to [base]'s own kind via
/// [_atDate].
DateTime _shiftByDays(DateTime base, int days) {
  final calendarDay =
      DateTime.utc(base.year, base.month, base.day).add(Duration(days: days));
  return _atDate(base,
      year: calendarDay.year, month: calendarDay.month, day: calendarDay.day);
}

/// [base] shifted by [months] whole calendar months (>= 0), keeping the
/// same day-of-month and wall-clock time — or `null` if that day doesn't
/// exist in the target month (the 31st-of-the-month rule; see file doc).
DateTime? _shiftByMonths(DateTime base, int months) {
  final totalMonths = (base.month - 1) + months;
  final year = base.year + totalMonths ~/ 12;
  final month = totalMonths % 12 + 1;
  final daysInTargetMonth = DateTime.utc(year, month + 1, 0).day;
  if (base.day > daysInTargetMonth) return null;
  return _atDate(base, year: year, month: month, day: base.day);
}

/// Lazily yields raw candidate occurrence instants in ascending order,
/// starting at [dtstart], ignoring `COUNT`/`UNTIL`/range bounds entirely
/// (those are applied by [_occurrencesInRange]). For an unbounded rule
/// this is an infinite (but lazily-pulled) sequence — see the file doc's
/// laziness section.
Iterable<DateTime> _rawCandidates(_ParsedRecurrence r, DateTime dtstart) sync* {
  switch (r.freq) {
    case _Freq.daily:
      var n = 0;
      while (true) {
        yield _shiftByDays(dtstart, n * r.interval);
        n++;
      }
    case _Freq.weekly:
      final days = r.byDay.isEmpty ? {dtstart.weekday} : r.byDay;
      final offsets = days.map((wd) => (wd - r.weekStart) % 7).toList()..sort();
      final firstWeekStart =
          _shiftByDays(dtstart, -((dtstart.weekday - r.weekStart) % 7));
      var week = 0;
      while (true) {
        if (week % r.interval == 0) {
          for (final offset in offsets) {
            final candidate = _shiftByDays(firstWeekStart, week * 7 + offset);
            if (!candidate.isBefore(dtstart)) {
              yield candidate;
            }
          }
        }
        week++;
      }
    case _Freq.monthly:
      var n = 0;
      while (true) {
        final candidate = _shiftByMonths(dtstart, n * r.interval);
        if (candidate != null) yield candidate;
        n++;
      }
  }
}

/// Applies `COUNT`/`UNTIL` (global series limits) and the queried range
/// (a local window into that series) to the lazy candidate sequence,
/// pulling only as many candidates as needed to either exhaust the series
/// or pass [rangeEnd] — never materializing the whole series.
List<DateTime> _occurrencesInRange(
  _ParsedRecurrence r,
  DateTime dtstart,
  DateTime rangeStart,
  DateTime rangeEnd,
) {
  final result = <DateTime>[];
  var produced = 0;
  for (final candidate in _rawCandidates(r, dtstart)) {
    if (r.count != null && produced >= r.count!) break;
    if (r.until != null && !r.until!.includes(candidate)) break;
    produced++;

    if (candidate.isAfter(rangeEnd)) break;
    if (!candidate.isBefore(rangeStart)) {
      result.add(candidate);
    }
  }
  return result;
}
