/// KUNIM local database (Drift), schema version 1.
///
/// NOTE: `app_database.g.dart` is generated by
/// `dart run build_runner build --delete-conflicting-outputs` and does NOT
/// exist yet in this hand-written Phase-0 skeleton — `_$AppDatabase` and
/// row/companion classes will only resolve once that generator has run
/// with Flutter/Dart installed.
library;

import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
// Referenced only from generated code: every [SyncColumns.id] column's
// `clientDefault` (`tables/sync_column_mixin.dart`) is re-emitted by
// `drift_dev` verbatim into `app_database.g.dart`, which is `part of` this
// library — so `Uuid` must be imported here, not just in the mixin's file.
import 'package:uuid/uuid.dart'; // ignore: unused_import

import 'tables/calendar_events_table.dart';
import 'tables/goals_table.dart';
import 'tables/habits_table.dart';
import 'tables/preferences_table.dart';
import 'tables/tasks_table.dart';

part 'app_database.g.dart';

/// Outbox for the offline-first sync engine (see `docs/plan.md` section 3).
/// Every local write that must reach the server is appended here in the
/// SAME transaction as the row write itself — a repository must never
/// write a row without also writing its outbox entry.
class SyncOutbox extends Table {
  IntColumn get seq => integer().autoIncrement()();
  TextColumn get entity => text()();
  TextColumn get rowId => text()();
  TextColumn get op => text()();
  TextColumn get payload => text()();
  IntColumn get attempts => integer().withDefault(const Constant(0))();
  TextColumn get lastError => text().nullable()();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

/// Small generic key/value store for local-only flags and settings that
/// do not warrant their own table (e.g. onboarding completion, last sync
/// cursor before `core/sync` owns it in a later phase).
class KeyValue extends Table {
  TextColumn get key => text()();
  TextColumn get value => text()();

  @override
  Set<Column> get primaryKey => {key};
}

@DriftDatabase(
  tables: [
    SyncOutbox,
    KeyValue,
    Preferences,
    TaskCategories,
    Tasks,
    CalendarEvents,
    Habits,
    HabitLogs,
    Goals,
    Milestones,
  ],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  /// For tests / DAOs that want to inject a custom executor (e.g. an
  /// in-memory database), per `docs/plan.md` section 13 testing strategy.
  AppDatabase.withExecutor(super.executor);

  @override
  int get schemaVersion => 2;

  /// Version 1 → 2 (this phase): adds the phase-2 sync tables — `tasks`,
  /// `task_categories`, `calendar_events`, `habits`, `habit_logs`, `goals`,
  /// `milestones` (`docs/plan.md` §3 sync table list). All seven are brand
  /// new tables, so the upgrade step is purely additive; nothing existing
  /// is altered or dropped.
  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (Migrator m) async {
          await m.createAll();
        },
        onUpgrade: (Migrator m, int from, int to) async {
          if (from < 2) {
            await m.createTable(taskCategories);
            await m.createTable(tasks);
            await m.createTable(calendarEvents);
            await m.createTable(habits);
            await m.createTable(habitLogs);
            await m.createTable(goals);
            await m.createTable(milestones);
          }
        },
      );

  static QueryExecutor _openConnection() {
    return driftDatabase(
      name: 'kunim',
      // TODO(Phase-1): supply the SQLCipher encryption key here once
      // `flutter_secure_storage` holds a per-install random key (see
      // docs/plan.md section 11, "SQLCipher, har o'rnatish uchun tasodifiy
      // kalit"). `drift_flutter`'s exact encryption hook API was not
      // verified against a pinned package version in this Phase-0 pass —
      // see PLATFORM-SETUP.md / task risk notes before relying on it.
    );
  }
}

/// Riverpod provider for the single [AppDatabase] instance. Features must
/// depend on DAOs built on top of this, never open their own connection.
final appDatabaseProvider = Provider<AppDatabase>((ref) {
  final db = AppDatabase();
  ref.onDispose(db.close);
  return db;
});
